baseURL = "/"
languageCode = "en-us"
title = "99devops"
theme = "hugo-ink"
paginate = 5

copyright = "© Copyright notice"
pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "G-80Q0R3FJ82"
disqusShortname = "ink-demo"

[params]
	subtitle = "A Highly trained monkey who loves doing SRE and DevOps"

	# Optional 64x64 avatar image.
	avatar = "https://image.freepik.com/free-vector/young-man-head-with-beard-avatar-character_24877-36786.jpg"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2


[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/99devops"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://www.twitter.com/99devops"

[[params.social]]
name = "Facebook"
icon = "facebook"
url = "https://www.facebook.com/99devops"

[taxonomies]
   tag = "tags"
